import { Board, Column, Label, Task, User } from "./types";

export const currentUserId = "u1";

export const users: User[] = [
  { id: "u1", name: "Mamun Rashid", email: "mamun@company.io", color: "#5750F1", initials: "MR" },
  { id: "u2", name: "Priya Nair", email: "priya@company.io", color: "#C97B1D", initials: "PN" },
  { id: "u3", name: "Diego Ferreira", email: "diego@company.io", color: "#2F9E5B", initials: "DF" },
  { id: "u4", name: "Amina Yusuf", email: "amina@company.io", color: "#D64545", initials: "AY" },
  { id: "u5", name: "Sora Kim", email: "sora@company.io", color: "#3B82C4", initials: "SK" },
];

export const labels: Label[] = [
  { id: "l1", name: "Backend", color: "#5750F1" },
  { id: "l2", name: "Frontend", color: "#2F9E5B" },
  { id: "l3", name: "Billing", color: "#C97B1D" },
  { id: "l4", name: "Bug", color: "#D64545" },
  { id: "l5", name: "Design", color: "#3B82C4" },
  { id: "l6", name: "Infra", color: "#8B5CF6" },
];

export const boards: Board[] = [
  {
    id: "b1",
    name: "Billing & Payments",
    description: "Subscription billing, invoicing, and payment provider work",
    color: "#5750F1",
    ownerId: "u1",
    members: [
      { userId: "u1", role: "owner" },
      { userId: "u2", role: "editor" },
      { userId: "u3", role: "editor" },
      { userId: "u4", role: "viewer" },
    ],
    columnIds: ["c1", "c2", "c3", "c4"],
  },
  {
    id: "b2",
    name: "Design System",
    description: "Shared component library and design tokens",
    color: "#3B82C4",
    ownerId: "u5",
    members: [
      { userId: "u5", role: "owner" },
      { userId: "u1", role: "editor" },
    ],
    columnIds: ["c5", "c6", "c7"],
  },
];

export const columns: Column[] = [
  { id: "c1", title: "Backlog", order: 0, color: "#8F8F98" },
  { id: "c2", title: "In Progress", order: 1, color: "#5750F1", wipLimit: 4 },
  { id: "c3", title: "In Review", order: 2, color: "#C97B1D" },
  { id: "c4", title: "Done", order: 3, color: "#2F9E5B" },

  { id: "c5", title: "To Do", order: 0, color: "#8F8F98" },
  { id: "c6", title: "In Progress", order: 1, color: "#3B82C4" },
  { id: "c7", title: "Shipped", order: 2, color: "#2F9E5B" },
];

export const tasks: Task[] = [
  {
    id: "t1",
    key: "BIL-142",
    title: "Add proration support for mid-cycle plan upgrades",
    description:
      "When a customer upgrades plans mid-cycle, calculate the prorated charge for the remainder of the billing period.",
    columnId: "c2",
    order: 0,
    priority: "high",
    labelIds: ["l1", "l3"],
    assigneeIds: ["u1"],
    dueDate: "2026-09-12",
    subtasksDone: 2,
    subtasksTotal: 5,
    commentCount: 3,
  },
  {
    id: "t2",
    key: "BIL-138",
    title: "Retry failed card payments with exponential backoff",
    columnId: "c2",
    order: 1,
    priority: "urgent",
    labelIds: ["l1", "l3"],
    assigneeIds: ["u3"],
    dueDate: "2026-09-08",
    subtasksDone: 1,
    subtasksTotal: 3,
    commentCount: 5,
  },
  {
    id: "t3",
    key: "BIL-151",
    title: "Show upcoming invoice preview on the billing settings page",
    columnId: "c2",
    order: 2,
    priority: "medium",
    labelIds: ["l2"],
    assigneeIds: ["u2"],
    subtasksDone: 0,
    subtasksTotal: 4,
  },
  {
    id: "t4",
    key: "BIL-119",
    title: "Reconcile Stripe webhook events with local ledger",
    columnId: "c3",
    order: 0,
    priority: "high",
    labelIds: ["l1", "l6"],
    assigneeIds: ["u3", "u1"],
    dueDate: "2026-09-06",
    commentCount: 8,
  },
  {
    id: "t5",
    key: "BIL-127",
    title: "Fix currency rounding error on annual invoices",
    columnId: "c3",
    order: 1,
    priority: "urgent",
    labelIds: ["l4", "l3"],
    assigneeIds: ["u1"],
    dueDate: "2026-09-07",
    commentCount: 2,
  },
  {
    id: "t6",
    key: "BIL-98",
    title: "Add dunning email sequence for expired cards",
    columnId: "c1",
    order: 0,
    priority: "medium",
    labelIds: ["l3"],
    assigneeIds: [],
    subtasksTotal: 6,
  },
  {
    id: "t7",
    key: "BIL-103",
    title: "Support multi-currency pricing tables",
    columnId: "c1",
    order: 1,
    priority: "low",
    labelIds: ["l1", "l3"],
    assigneeIds: ["u2"],
  },
  {
    id: "t8",
    key: "BIL-110",
    title: "Research usage-based billing providers",
    columnId: "c1",
    order: 2,
    priority: "low",
    labelIds: ["l3"],
    assigneeIds: [],
  },
  {
    id: "t9",
    key: "BIL-95",
    title: "Migrate legacy invoices table to new schema",
    columnId: "c1",
    order: 3,
    priority: "medium",
    labelIds: ["l1", "l6"],
    assigneeIds: ["u3"],
    dueDate: "2026-09-20",
  },
  {
    id: "t10",
    key: "BIL-87",
    title: "Launch self-serve plan downgrade flow",
    columnId: "c4",
    order: 0,
    priority: "medium",
    labelIds: ["l2", "l3"],
    assigneeIds: ["u2", "u4"],
    subtasksDone: 6,
    subtasksTotal: 6,
    commentCount: 4,
  },
  {
    id: "t11",
    key: "BIL-82",
    title: "Add tax rate lookup by billing address",
    columnId: "c4",
    order: 1,
    priority: "high",
    labelIds: ["l1"],
    assigneeIds: ["u1"],
    subtasksDone: 4,
    subtasksTotal: 4,
  },

  {
    id: "t12",
    key: "DS-41",
    title: "Define elevation and shadow scale",
    columnId: "c5",
    order: 0,
    priority: "low",
    labelIds: ["l5"],
    assigneeIds: ["u5"],
  },
  {
    id: "t13",
    key: "DS-44",
    title: "Build accessible Combobox component",
    columnId: "c6",
    order: 0,
    priority: "medium",
    labelIds: ["l2", "l5"],
    assigneeIds: ["u1"],
    subtasksDone: 3,
    subtasksTotal: 5,
  },
  {
    id: "t14",
    key: "DS-39",
    title: "Ship dark theme tokens v2",
    columnId: "c7",
    order: 0,
    priority: "medium",
    labelIds: ["l5"],
    assigneeIds: ["u5"],
    commentCount: 1,
  },
];
